### PR TITLE
Add Dockerfile and container build workflow

### PR DESCRIPTION
**Pull request by nikdoof**
I'm in the process of setting up this script to run within my Kubernetes Mastodon instance and needed it packaging up for ease of use. So I thought I'd contribute back the changes.

This adds the following

* Dockerfile to generate the container
* A new Github workflow to build and publish the container on ghcr.io 

The script is provided as a entry point, so the container can be used with `docker run containername --server=mastodon.social ...`.

### CODE REVIEW

**Comment by nanos** [comment]
That's pretty cool. Thanks so much!

Can you add a section on how to use this with Docker to the README please? I'm not familiar with docker, so can't do it myself.

Once that's added I'll very happily merge this PR.

**Comment by nikdoof** [comment]
@nanos Done, added a k8s example CronJob for running the container as well.

**Comment by nanos** [comment]
Amazing! Thank you so much!

**Comment by nanos** [comment]
Actually, I just realised a couple of issues after I merged:

 - This link is a `404`: `https://github.com/nanos/mastodon_get_replies/pkgs/container/mastodon_get_replies`
 - As far as I can see the will try to run the Build Container workflow, every time I release a version. Any way to adjust this to only execute if needed / configured?

**Comment by nikdoof** [comment]
The 404 will fix itself once the container has built (as it's the URL for the container view on Github, e.g. https://github.com/nikdoof/mastodon_get_replies/pkgs/container/mastodon_get_replies).

You can modify the 'on' section of [the workflow](https://github.com/nanos/mastodon_get_replies/blob/27415bdff6c9e1496d7fc576873d5f82c471ae11/.github/workflows/build-container.yaml#L5) to restrict its run, if you only want it on a tagged version then remove the branch: main bit.

As for the error on the first run, it may be that the repo doesn't allow Actions to write to the repo: Go to Settings -> Actions -> General, then in the "Workflow permissions" set it to Read/Write.

**Comment by nanos** [comment]
Yep, the permissions were indeed the problem.

I now need to think about how I'll deal with this, because there are 54 forks for this repo. I don't think we'll want them all to run the Action to build the container. That makes no sense. 

I'll have a look at the workflow 'on' bit to see what I can do to fix that

**Comment by nanos** [comment]
I think as long as I simply remove the branch: main bit, it should be fine, unless forks do their own releases, in which case, again, it's fine.

Thanks again for doing this!
Much appreciated!

**Pull request merged**
